-- MySQL Script generated by MySQL Workbench
-- Sat Jul  5 13:13:23 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `e_mail` VARCHAR(250) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contrato` (
  `id_contrato` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `status` TINYINT NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_contrato`, `cliente_id_cliente`),
  INDEX `fk_contrato_cliente_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_contrato_cliente`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cartao` (
  `id_cartao` INT NOT NULL AUTO_INCREMENT,
  `numero_cartao` VARCHAR(19) NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `anuidade` DOUBLE NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `bandeira` VARCHAR(45) NOT NULL,
  `contrato_id_contrato` INT NOT NULL,
  `contrato_cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_cartao`, `contrato_id_contrato`, `contrato_cliente_id_cliente`),
  INDEX `fk_cartao_contrato1_idx` (`contrato_id_contrato` ASC, `contrato_cliente_id_cliente` ASC) VISIBLE,
  UNIQUE INDEX `id_cartao_UNIQUE` (`id_cartao` ASC) VISIBLE,
  CONSTRAINT `fk_cartao_contrato1`
    FOREIGN KEY (`contrato_id_contrato` , `contrato_cliente_id_cliente`)
    REFERENCES `mydb`.`contrato` (`id_contrato` , `cliente_id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
